mysite/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'mysite'
urlpatterns = [
    path('', views.mysite_home, name='home'),
    path('gallery/', views.mysite_gallery, name='gallery'),
    path('gallery/<str:image_slug>/', views.mysite_view_image, name='view_image'),
    path('contact-me/', views.mysite_contact_me, name='contact_me'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/models.py
from django.db import models
from django.utils import timezone


class CustomPage(models.Model):
    id = models.AutoField(primary_key=True)
    text = models.CharField(verbose_name="Page",
                            max_length=50,
                            unique=True)

    def __str__(self):
        return self.text


class CustomText(models.Model):
    type = models.OneToOneField(CustomPage,
                                on_delete=models.CASCADE, )
    text = models.TextField(verbose_name="Description")


def gallery_image_path(file, filename):
    date = timezone.datetime.now()
    file_path = 'gallery\\{year}\\{month}\\{name}'.format(
        year=date.year,
        month=date.month,
        name=filename, )
    return file_path


class GalleryImage(models.Model):
    id = models.AutoField(primary_key=True)
    path = models.ImageField(upload_to=gallery_image_path)
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField(default=None,
                                   null=True)

    def __str__(self):
        return self.title

    @property
    def slug_me(self):
        return "-".join(self.title.split())


class GalleryVideo(models.Model):
    id = models.AutoField(primary_key=True)
    path = models.CharField(max_length=400)


def home_banner_path(file, filename):
    date = timezone.datetime.now()
    file_path = 'home_banner\\{year}\\{month}\\{name}'.format(
        year=date.year,
        month=date.month,
        name=filename, )
    return file_path


class HomeBanner(models.Model):
    id = models.AutoField(primary_key=True)
    path = models.ImageField(upload_to=home_banner_path)
    alt = models.CharField(max_length=100)

    def __str__(self):
        return self.alt

mysite/forms.py
from django import forms
from crispy_forms.helper import FormHelper


class ContactForm(forms.Form):
    helper = FormHelper()
    helper.form_show_labels = False
    name = forms.CharField(required=False, max_length=100, help_text="Name")
    email = forms.EmailField(required=True, help_text="Email")
    phone = forms.CharField(required=False, max_length=10, help_text="Phone")
    text = forms.CharField(required=True, widget=forms.Textarea, help_text="Message")


mysite/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings
from .forms import ContactForm
from .models import *


def mysite_home(request):
    banners = HomeBanner.objects.all()
    context = {"test{}".format(banners[0].id): banners[0],
               "test{}".format(banners[1].id): banners[1],
               "test{}".format(banners[2].id): banners[2], }
    template = 'mysite/home.html'
    return render(request, template, context)


def mysite_gallery(request):
    gallery_all = GalleryImage.objects.all()
    context = {'gallery': gallery_all, }
    template = 'mysite/gallery.html'
    return render(request, template, context)


def mysite_view_image(request, image_slug):
    un_slug = " ".join(image_slug.split("-"))
    image_view = GalleryImage.objects.get(title=un_slug)
    context = {'image_view': image_view, }
    template = 'mysite/view_image.html'
    return render(request, template, context)


def mysite_contact_me(request):
    title = 'Contact'
    form = ContactForm(request.POST or None)
    confirm_message = None
    contact_me = CustomText.objects.get(type=2)
    if form.is_valid():
        name = form.cleaned_data['name']
        text = form.cleaned_data['text']
        subject = 'Message from mysite'
        email_from = form.cleaned_data['email']
        message = 'name:\t{}\nemail:\t{}\nmessage:\t{}'.format(name, email_from, text)
        email_to = [settings.EMAIL_HOST_USER]

        send_mail(
            subject,
            message,
            email_from,
            [email_to, ],
            fail_silently=False,
        )

        title = 'Message sent.'
        confirm_message = 'Thank you for messaging us. We will reply shortly.'
        form = None

    context = {'title': title,
               'contact_me': contact_me,
               'form': form,
               'confirm_message': confirm_message, }

    template = 'mysite/contact_me.html'
    return render(request, template, context)

mysite/templates/mysite/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        {% block title %}
        {% endblock %}
    </title>

    <meta charset="UTF-8">
    <meta name="author" content="Vo Media">
    <meta name="description" content="Dinh Did It">
    <meta name="keywords" content="Photography, Video Production">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="stylesheet" href="{% static "mysite/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "mysite/mystyle.css" %}">

</head>
<body>
<body>

<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url "mysite:home" %}">VO MEDIA</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "mysite:gallery" %}">GALLERY</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "mysite:contact_me" %}">CONTACT</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!--Page body-->
{% block content %}
{% endblock %}
<!--/.Page body-->

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="d-flex justify-content-center"><a href="#">Back to top</a></p>
        <p class="m-0 text-center text-white">Copyright &copy; VO MEDIA 2019</p>
    </div>

    <!-- /.container -->
</footer>


<script src="{% static "mysite/jquery-3.2.1.slim.min.js" %}"></script>
<script src="{% static "mysite/popper.min.js" %}"></script>
<script src="{% static "mysite/bootstrap.min.js" %}"></script>
</body>
</html>

mysite/templates/mysite/contact_me.html
{% extends 'mysite/base.html' %}
{% load crispy_forms_tags %}
{% crispy form form.helper %}

{% block title %}
    Contact Me
{% endblock %}

{% block nav-one %}{% endblock %}
{% block nav-two %}{% endblock %}
{% block nav-three %}{% endblock %}
{% block nav-four %}active{% endblock %}

{% block content %}

    <div class="row" style="padding-top: 25px; width: 100%;">
        <div class="col-lg-4 offset-lg-4">
            <h1 style="color: black;">Contact</h1>
            {% if confirm_message %}
                <h2>{{ title }}</h2>
                {{ confirm_message }}
            {% endif %}
            {% if form %}
                <form style="color: black;" method="post" action="">
                {% csrf_token %}
                {% crispy form %}
                <input type="submit" value="SEND" class="btn btn-default" style="margin-bottom: 4.6rem;">
            {% endif %}

            </form>
        </div>
    </div>
{% endblock %}

mysite/templates/mysite/gallery.html
{% extends 'mysite/base.html' %}


{% block title %}
    Gallery
{% endblock %}

{% block nav-one %}{% endblock %}
{% block nav-two %}active{% endblock %}
{% block nav-three %}{% endblock %}
{% block nav-four %}{% endblock %}

{% block content %}
    <div class="container">
    <br>
        <div class="row">
            {% for image in gallery %}
                <div class="gallery_product col-lg-4 col-md-4 col-sm-4 col-xs-6">
                    <a href="{% url "mysite:view_image" image.slug_me %}" data-size="1600x1067">
                        <img alt="{{ image.title }}" src="{{ image.path.url }}" class="img-fluid z-depth-1">
                    </a>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

mysite/templates/mysite/home.html
{% extends "mysite/base.html" %}
{% load static %}
{% block title %}
    Home
{% endblock %}

{% block nav-one %}active{% endblock %}
{% block nav-two %}{% endblock %}
{% block nav-three %}{% endblock %}
{% block nav-four %}{% endblock %}

{% block content %}
    <!-- Carousel -->
    <header>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <!-- Slide One - Set the background image for this slide in the line below -->
                <div class="carousel-item active" style="background-image: url('http://placehold.it/1900x1080')">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Family</h3>
                        <p></p>
                    </div>
                </div>
                <!-- Slide Two - Set the background image for this slide in the line below -->
                <div class="carousel-item" style="background-image: url('http://placehold.it/1900x1080')">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Business</h3>
                        <p></p>
                    </div>
                </div>
                <!-- Slide Three - Set the background image for this slide in the line below -->
                <div class="carousel-item" style="background-image: url('http://placehold.it/1900x1080')">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Entertainment</h3>
                        <p></p>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </header>
    <!-- /.Carousel -->

    <!-- Page Content -->
    <div class="container">

        <h1 class="my-4">VERY OFTEN MEDIA</h1>

        <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-lg-4 mb-4">
                <div class="card h-100">
                    <h4 class="card-header">FAMILY</h4>
                    <div class="card-body">
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-4">
                <div class="card h-100">
                    <h4 class="card-header">BUSINESS</h4>
                    <div class="card-body">
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-4">
                <div class="card h-100">
                    <h4 class="card-header">ENTERTAINMENT</h4>
                    <div class="card-body">
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->
        <hr>
    </div>
    <!-- /.container -->
{% endblock %}

mysite/templates/mysite/view_image.html
{% extends 'mysite/base.html' %}

{% block title %}
    View Image
{% endblock %}

{% block content %}
    <p> Dinh Did It</p>
    <p> {{ image_view.title }}</p>
    <p>
    <img class="img-fluid" src="{{ image_view.path.url }}" alt="{{ image_view.title }}">
    </p>
    <p>
    {{ image_view.description }}
    </p>
{% endblock %}